services:
  api:
    ports: !reset []
    networks:
      - proxy
      - default
      
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.docgen-api.rule=Host(`api.docgen.ccm.local`)"
      - "traefik.http.routers.docgen-api.entrypoints=websecure"
      - "traefik.http.routers.docgen-api.tls=true"
      - "traefik.http.services.docgen-api.loadbalancer.server.port=8000"
      - "traefik.docker.network=proxy"

  frontend:
    ports: !reset []
    volumes: !reset []
    networks:
      - proxy
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.docgen-front.rule=Host(`docgen.ccm.local`)"
      - "traefik.http.routers.docgen-front.entrypoints=websecure"
      - "traefik.http.routers.docgen-front.tls=true"
      - "traefik.http.services.docgen-front.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
